### PR TITLE
Adding a documentation file that includes the Input JSON formats, and the output YOLO format

### PR DESCRIPTION
**Pull request by vsnupoudel**
Added a new markdown file that outlines how each input JSON formats look like.
1. Infolks JSON
2. Vott JSON
3. COCO JSON
4. YOLO text files

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Documentation update: Added a comprehensive guide for different annotation formats supported by JSON2YOLO.

### 📊 Key Changes
- Introduced a new `Annotation_Formats.md` file with detailed descriptions of supported annotation formats.
- Formats covered include INFOLKS, VOTT, COCO, and YOLO.
- Sample JSON structures provided for each annotation format.

### 🎯 Purpose & Impact
- 📚 **Educational Resource:** Provides users with clear information on various annotation formats, helping them understand how to structure annotation data.
- 🚀 **Enhances Usability:** Eases the conversion process for users by offering direct examples and explanations.
- 💡 **Improved Documentation:** Ensures that both new and experienced users can readily access and use differing annotation formats effectively.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @vsnupoudel, thank you for submitting a PR to the `ultralytics/JSON2YOLO` repository! 🚀 We're thrilled to see your contribution and would like to guide you through the next steps to ensure a smooth integration:

- ✅ **Define a Purpose**: You've added a valuable documentation file detailing input JSON and output YOLO formats. Ensure your PR description clearly communicates this purpose, possibly linking to any relevant [issues](https://github.com/ultralytics/JSON2YOLO/issues) if there are any.
- ✅ **Synchronize with Source**: Please ensure your branch is up-to-date with the `main` branch of `ultralytics/JSON2YOLO`. You can do this by clicking 'Update branch' on GitHub or running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify that all continuous integration checks are passing. If any checks fail, please address the issues. You can learn more about our CI process [here](https://docs.ultralytics.com/help/CI/).
- ✅ **Update Documentation**: You have already added an excellent `Annotation_Formats.md` document. Make sure it aligns with the rest of our [documentation](https://docs.ultralytics.com).
- ✅ **Add Tests**: If applicable, consider recommending tests that validate the correctness of the newly documented formats, ensuring robustness in the conversion process.
- ✅ **Sign the CLA**: If this is your first contribution, don't forget to sign our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by affirming with "I have read the CLA Document and I sign the CLA."
- ✅ **Minimize Changes**: Aim to keep your changes focused on the documentation enhancement to ensure clean integration.

For additional guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). An Ultralytics engineer will review your PR and provide feedback soon. Thank you for helping us enhance the usability and education around JSON2YOLO! ⭐️

Keep up the great work and feel free to reach out if you have any questions. 🙌

**Comment by pderrenger** [comment]
@vsnupoudel thank you for your contribution! The addition of the `Annotation_Formats.md` file will be a valuable resource for users working with different annotation formats. Your effort in enhancing the documentation is much appreciated.

**Review by glenn-jocher — APPROVED** [review]

**Comment by vsnupoudel** [comment]
Thank you.

**Comment by vsnupoudel** [comment]
reopening, as there seems to be a problem merging, due to changes in 'format.yml' file.

**Comment by pderrenger** [comment]
@vsnupoudel you're welcome! If you have any further questions or need clarification, feel free to ask. The YOLO community and the Ultralytics team are here to help.

**Pull request closed without merging**
